### ISSUE TITLE
window7系统，<python web 开发实践 >267页运行错误，什么原因？

### ISSUE THREAD

**Issue by 744216212** [dongweiming/web_develop#46]
(venv) E:\chapter9\section3>celery -A proj worker -l info

 -------------- celery@USERCHI-MF1B2NM v4.0.2 (latentcall)
---- **** -----
--- * ***  * -- Windows-7-6.1.7601-SP1 2017-01-05 17:14:05
-- * - **** ---
- ** ---------- [config]
- ** ---------- .> app:         proj:0x2df5090
- ** ---------- .> transport:   amqp://dongwm:**@localhost:5672/web_develop
- ** ---------- .> results:     redis://localhost:6379/0
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery

[tasks]
  . proj.tasks.add
  . proj.tasks.div

[2017-01-05 17:14:05,279: CRITICAL/MainProcess] Unrecoverable error: TypeError('
must be integer<k>, not _subprocess_handle',)
Traceback (most recent call last):
  File "e:\flasky\venv\lib\site-packages\celery\worker\worker.py", line 203, in
start
    self.blueprint.start(self)
  File "e:\flasky\venv\lib\site-packages\celery\bootsteps.py", line 119, in star
t
    step.start(parent)
  File "e:\flasky\venv\lib\site-packages\celery\bootsteps.py", line 370, in star
t
    return self.obj.start()
  File "e:\flasky\venv\lib\site-packages\celery\concurrency\base.py", line 131,
in start
    self.on_start()
  File "e:\flasky\venv\lib\site-packages\celery\concurrency\prefork.py", line 11
2, in on_start
    **self.options)
  File "e:\flasky\venv\lib\site-packages\billiard\pool.py", line 1008, in __init
__
    self._create_worker_process(i)
  File "e:\flasky\venv\lib\site-packages\billiard\pool.py", line 1117, in _creat
e_worker_process
    w.start()
  File "e:\flasky\venv\lib\site-packages\billiard\process.py", line 122, in star
t
    self._popen = self._Popen(self)
  File "e:\flasky\venv\lib\site-packages\billiard\context.py", line 383, in _Pop
en
    return Popen(process_obj)
  File "e:\flasky\venv\lib\site-packages\billiard\popen_spawn_win32.py", line 64
, in __init__
    _winapi.CloseHandle(ht)
TypeError: must be integer<k>, not _subprocess_handle

(venv) E:\chapter9\section3>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "e:\flasky\venv\lib\site-packages\billiard\spawn.py", line 159, in spawn_
main
    new_handle = steal_handle(parent_pid, pipe_handle)
  File "e:\flasky\venv\lib\site-packages\billiard\reduction.py", line 121, in st
eal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
WindowsError: [Error 87]

**Comment by dongweiming** [comment]
@744216212 http://docs.celeryproject.org/en/latest/faq.html#does-celery-support-windows celery4开始不再官网支持windows了

**Comment by 744216212** [comment]
非常感谢！
