### ISSUE TITLE
chapter9/section2/amqp_consumer.py 第九章P257页运行出错

### ISSUE THREAD

**Issue by fengdwx** [dongweiming/web_develop#78]
第九章P257页，启动消费者的时候，就会报错
Traceback (most recent call last):
  File "amqp_consumer.py", line 25, in <module>
    channel.basic_consume(on_message, 'standard')  # 订阅队列
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1617, in basic_consume
    validators.require_string(queue, 'queue')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pika/validators.py", line 17, in require_string
    value,
TypeError: queue must be a str or unicode str, but got <function on_message at 0x7f8ab01bd758>
说应该是一个字符串，但是on_message是一个函数

**Comment by fengdwx** [comment]
channel.basic_consume后面接的参数顺序错误了
应该是先queue的名字，第二个参数是回调函数
应该是channel.basic_consume('standard', on_message)
