### ISSUE TITLE
第3章 P34 自定义URL转换器

### ISSUE THREAD

**Issue by MrCJJW** [dongweiming/web_develop#9]
```
import urllib

from flask import Flask
from werkzeug.routing import BaseConverter

app = Flask(__name__)


class ListConverter(BaseConverter):

    def __init__(self, url_map, separator='+'):
        super(ListConverter, self).__init__(url_map)
        self.separator = urllib.unquote(separator)

    def to_python(self, value):
        return value.split(self.separator)

    def to_url(self, values):
        return self.separator.join(BaseConverter.to_url(value)
                                   for value in values)


app.url_map.converters['list'] = ListConverter


@app.route('/list1/<list:page_names>/')
def list1(page_names):
    return 'Separator: {} {}'.format('+', page_names)


@app.route('/list2/<list(separator=u"|"):page_names>/')
def list2(page_names):
    return 'Separator: {} {}'.format('|', page_names)


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=9000)
```

`BaseConverter.to_url(value)`
是否改为
`BaseConverter.to_url(self,value)`或`super(ListConverter,self).to_url(value)`
因为to_url方法是一个对象方法，以下是BaseConverter的源码

```
class BaseConverter(object):

    """Base class for all converters."""
    regex = '[^/]+'
    weight = 100

    def __init__(self, map):
        self.map = map

    def to_python(self, value):
        return value

    def to_url(self, value):
        return url_quote(value, charset=self.map.charset)
```

不过flask源码的app.py文件有一段注释掉的自定义转换器示例代码，如下：

```
class ListConverter(BaseConverter):
    def to_python(self, value):
        return value.split(',')
    def to_url(self, values):
        return ','.join(BaseConverter.to_url(value)
                             for value in values)
```

里面也是没加self，是否也错了？
不过我在没修改的情况下调用`url_for('list1',page_names='ab')`就会出现
`TypeError: unbound method to_url() must be called with BaseConverter instance as first argument (got str instance instead)
`
望作者解答一下

**Comment by dongweiming** [comment]
@MrCJJW 是的 https://github.com/pallets/flask/pull/2039

url可以匹配是因为在 这里在 https://github.com/pallets/werkzeug/blob/master/werkzeug/routing.py#L696 实例化

**Comment by dongweiming** [comment]
感谢提交这么好的issue 👍

**Comment by dongweiming** [comment]
@MrCJJW 项目代码也改了 https://github.com/dongweiming/web_develop/commit/be7f3aa7d0120d7710f20b2b6e14008131f36c99

**Comment by dongweiming** [comment]
还有这个 https://github.com/dongweiming/web_develop/commit/b0c81d8a6d193c49cd5c98d0b12eeb099f387188

**Comment by dongweiming** [comment]
我这算是现场演示怎么「混」进Flask贡献者名单么...

**Comment by Vito-Wang** [comment]
@dongweiming `看到你最新版的书中已经修改了这个问题，代码修改后是这样的
```
def to_url(self, values):
        return self.separator.join(super(BaseConverter,self).to_url(value)
                                   for value in values)
````
让后我加了一个访问index页面的路由
```
@app.route('/')
def index():
    return url_for('list1', page_names='ab')
```
访问index页面的时候报错了，其他页面没问题，自认为是源码没弄懂的原因，实在找不出问题，求指导
```
Traceback (most recent call last):
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/app_with_custom_converter.py", line 38, in index
    return url_for('list1', page_names='ab')
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1756, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1671, in _partial_build
    append_unknown)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 1679, in _partial_build
    rv = rule.build(values, append_unknown)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 798, in build
    add(self._converters[data].to_url(values[data]))
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/app_with_custom_converter.py", line 21, in to_url
    for value in values)
  File "/home/vitowang/workspace/python-script/web_develop/chapter3/section1/app_with_custom_converter.py", line 21, in <genexpr>
    for value in values)
AttributeError: 'super' object has no attribute 'to_url'
```

**Comment by dongweiming** [comment]
@Vito-Wang 非常感谢反馈。 已经改成更好的 `BaseConverter.to_url(self, value)`了， 详见 https://github.com/dongweiming/web_develop/commit/bb542efea269758400c01dc0099ee235b3ebb83d 。 cc @MrCJJW
